name: Crear Contenedor de Evidencia

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v4

    - name: Iniciar sesion en GitHub Packages
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Construir y subir imagen Docker
      run: |
        # Convertimos el nombre del repositorio a minúsculas para cumplir con la regla de Docker
        REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        docker build -t ghcr.io/$REPO_LOWER:latest .
        docker push ghcr.io/$REPO_LOWER:latest
